#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

#runApplication decomposePar 

#runParallel simpleFoam
runApplication simpleFoam

# reconstructPar -latestTime
runApplication postProcess -func 'mag(U)' -latestTime


#------------------------------------------------------------------------------
