template_path = "./template"
case_path = "./cases"
output_path = "./output"
ux_uy_clim = [-6,6]
uz_clim = [-2,2]


building_template = """
    building_1
    {
        type searchableBox;
        min  ($b1x0 $b1y0 $b1z0);
        max  ($b1x1 $b1y1 $b1z1);
    }

    building_2
    {
        type searchableBox;
        min  ($b2x0 $b2y0 $b2z0);
        max  ($b2x1 $b2y1 $b2z1);
    }

    skywalk
    {
        type searchableBox;
        min  ($swx0 $swy0 $swz0);
        max  ($swx1 $swy1 $swz1);
    }
"""

inflow_increment = 45

abl_template = """
zDir        (0 0 1);      
Uref        5.0;
Zref        10;           
z0          uniform 0.03;
d           uniform 0.0;
flowDir     ($nx $ny 0);
"""

initial_template = """
flowVelocity         ($ux $uy 0);  
pressure             0;
turbulentKE          1.3;  
turbulentEpsilon     0.01; 
"""

[dimensions] # 810,000 combinations
building_1_z1 = [10, 20, 40, 60, 80, 100] # height of building 1
building_1_x = [10, 20, 40, 60, 80] # width of building 1
building_1_y1 = [10, 20, 40, 60, 80] # length of building 1
building_1_z2 = [0, 3] # vertical height from gound to base of building 1
building_1_y2 = [0, 10, 20] # Distance from y datum

building_2_z1 = [10, 20, 40, 60, 80, 100] # height of building 1
building_2_x = [10, 20, 40, 60, 80] # width of building 1
building_2_y1 = [10, 20, 40, 60, 80] # length of building 1
building_2_z2 = [0, 3] # vertical height from gound to base of building 2
building_2_y2 = [0, 10, 20] # Distance from y datum

skywalk_z1 = [3] # height of skywalk
skywalk_x = [20] # width of skywalk
skywalk_y = [3] # length of skywalk 1
skywalk_z2 = [6] # vertical height from gound to base of skywalk