template_path = "./template"
case_path = "./cases"

building_template = """
    building_1
    {
        type searchableBox;
        min  ($b1x0 $b1y0 0.0);
        max  ($b1x1 0.0 $b1z1);
    }

    building_2
    {
        type searchableBox;
        min  ($b2x0 $b2y0 0.0);
        max  ($b2x1 0.0 $b2z1);
    }

    skywalk
    {
        type searchableBox;
        min  ($swx0 $swy0 $swz0);
        max  ($swx1 0.0 $swz1);
    }
"""

inflow_increment = 45

abl_template = """
zDir        (0 0 1);      
Uref        5.0;
Zref        10;           
z0          uniform 0.03;
d           uniform 0.0;
flowDir     ($nx $ny 0);
"""

initial_template = """
flowVelocity         ($ux $uy 0);  
pressure             0;
turbulentKE          1.3;  
turbulentEpsilon     0.01; 
"""

[dimensions]
building_1_z= [100, 200] # height of building 1
building_1_x = [30] # width of building 1
building_1_y = [30] # length of building 1
# building_1_distance_from_datum = [1,1,1]

building_2_z = [50] # height of building 1
building_2_x = [20] # width of building 1
building_2_y = [20] # length of building 1
# building_2_distance_from_datum = [1,1,1]

skywalk_z1 = [5] # height of skywalk
skywalk_x = [20] # width of skywalk
skywalk_y = [5] # length of skywalk 1
skywalk_z2 = [15] # vertical height from gound to base of skywalk
# skywalk_distance_from_datum = [1,1,1]


